# Generated by Django 4.2 on 2023-05-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('brand_name', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('product_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('product_type', models.CharField(choices=[('gadget', 'gadget'), ('drug', 'drug')], default='drug', max_length=100)),
                ('quantity_available', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_bought', models.DateField(blank=True, null=True)),
                ('other_info', models.TextField(blank=True, default='None', null=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
    ]
